# Generated by Django 3.2 on 2021-04-24 05:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ubication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='state',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Código Zip')),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ubication.state')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['name', 'state'],
                'unique_together': {('name', 'state')},
            },
        ),
    ]
