# Generated by Django 3.2 on 2021-04-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ubication', '0002_auto_20210424_0016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
    ]
