# Generated by Django 3.2 on 2021-04-24 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Ubication', '0003_rename_state_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de Propiedad')),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=None, max_length=100, verbose_name='Ciudad')),
                ('image', models.ImageField(upload_to='images', verbose_name='Imagen')),
                ('price', models.IntegerField(blank=None, verbose_name='Precio')),
                ('baths', models.IntegerField(blank=None, verbose_name='No de Baños')),
                ('beds', models.IntegerField(blank=None, verbose_name='No de Habitaciones')),
                ('sqrt', models.IntegerField(blank=None, verbose_name='Mts2')),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.categories')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ubication.cities')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['titulo', 'price', 'city', 'sqrt', 'category'],
                'unique_together': {('titulo',)},
            },
        ),
    ]
