# Generated by Django 3.2 on 2021-04-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertiestypes',
            options={'ordering': ['name'], 'verbose_name': 'Tipo Propiedad', 'verbose_name_plural': 'Tipos de Propiedades'},
        ),
    ]
