# Generated by Django 3.2 on 2021-04-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_alter_propertiestypes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='titulo',
            field=models.CharField(blank=None, max_length=100, verbose_name='Titulo'),
        ),
    ]
