# Generated by Django 3.2 on 2021-04-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0004_alter_properties_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Property.propertiestypes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='transaction_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], default='Rent', max_length=10, verbose_name='Tipo de Transacción'),
            preserve_default=False,
        ),
    ]
